merge product listing page
piyushsh25/zevnon pull request #2
Opened 2022-02-14 11:36 UTC by piyushsh25

2022-02-15 05:05 UTC, GuptaEesh commented on docs/css/listing.css
> +    box-shadow: 2px 2px 1.5rem black;
can use css variable here

2022-02-15 05:06 UTC, GuptaEesh commented on docs/css/listing.css
> +    padding: 3rem 2rem 1rem;
I can see you have used --size variable in your code then please replace this too.
>Because it confuses reader whether you are using variables or not.

2022-02-15 05:08 UTC, GuptaEesh commented on docs/css/listing.css
> +.shopping-section .card .text-div .header-bottom .selling-price {
you don't have to be so specific while doing this.
>Just 1 parent class or even without this, it should work.
I would suggest you refactor.

2022-02-15 05:08 UTC, GuptaEesh requested changes
Apart from changes asked, code looks fine.

2022-02-15 05:23 UTC, piyushsh25 commented on docs/css/listing.css
> +    box-shadow: 2px 2px 1.5rem black;
done!

2022-02-15 05:24 UTC, piyushsh25 commented on docs/css/listing.css
> +.shopping-section .card .text-div .header-bottom .selling-price {
done!

2022-02-15 05:24 UTC, piyushsh25 commented on docs/css/listing.css
> +    padding: 3rem 2rem 1rem;
done!

2022-02-15 06:34 UTC, GuptaEesh approved these changes
Thank you for applying the changes suggested.
Hope it helps you in writing cleaner code.
**Good to go.**

2022-02-15 11:53 UTC, AnuragSahu11 commented on docs/css/listing.css
> +    text-decoration: line-through;
You could create separate class for line through

2022-02-15 11:55 UTC, AnuragSahu11 approved these changes
good work , just a suggestion you can decrease the shadow in your product cards it seems a little too much, you can merge

2022-02-16 06:14 UTC, piyushsh25 commented on docs/css/listing.css
> +    text-decoration: line-through;
done!

2022-02-16 06:14 UTC, piyushsh25 commented
Made changes as per the suggestions. Merging

2022-02-16 06:14 UTC, merged